# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
  containerRegistry: 'nmpersonalregistry'

stages:
- stage: BuildAndPublish
  displayName: Build and Push Docket to Register then Publish of release pipeline
  jobs:     
  
  - job: Build
    steps:    
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'reactapp'
        dockerfile: 'Dockerfile'
        containerRegistry: 'nmpersonalregistry'
  - job: PreReleasePrepForhospitalMicroservice
    dependsOn: Build
    displayName: Pre Release Preparation (Bash build id and Publish for Release pipeline)
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
            
            
            value=`cat 'reactapp.yaml'`
            echo 'Hello world 0.25'  
            value=${value//##BUILD_ID##/$(Build.BuildId)}
            
            echo "$value" > 'reactapp_build.yaml'
            echo 'Hello world 1'  
            value1=`cat 'reactapp_build.yaml'`
            echo 'Hello world 2'  
            echo "$value1"
           
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: ''
        artifact: 'reactapp'
        publishLocation: 'pipeline'